In [1]:
import numpy as np
import cvxpy as cp
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
x = np.array([0.1, 0.2, -0.05, 0.1])
Sigma = cp.Variable((4, 4), symmetric=True)

problem = cp.Problem(cp.Maximize(x.T @ Sigma @ x), [Sigma[0,0] == 0.2, Sigma[1,1] == 0.1, Sigma[2,2] == 0.3, Sigma[3,3] == 0.1, 
                                                    Sigma[0,1] >=0, Sigma[0,2] >= 0, Sigma[1,2] <= 0, Sigma[1,3] <= 0, Sigma[2,3] >= 0, Sigma >> 0])
problem.solve()

0.01516610123309048

In [3]:
print('Worst-case sigma', np.sqrt(x.T @ Sigma.value @ x))
print('Sigma', Sigma.value)

Worst-case sigma 0.12315072567017411
Sigma [[ 2.00000000e-01  9.33324323e-02  9.31686603e-07  8.30130856e-02]
 [ 9.33324323e-02  1.00000000e-01 -1.09983027e-01 -6.03504496e-07]
 [ 9.31686603e-07 -1.09983027e-01  3.00000000e-01  1.77084868e-02]
 [ 8.30130856e-02 -6.03504496e-07  1.77084868e-02  9.99999995e-02]]


In [ ]:
np.diag(np.diag(Sigma.value))

array([[0.2, 0. , 0. , 0. ],
       [0. , 0.1, 0. , 0. ],
       [0. , 0. , 0.3, 0. ],
       [0. , 0. , 0. , 0.1]])

Diagonal Sigma

In [4]:
x = np.array([0.1, 0.2, -0.05, 0.1])
Sigma = cp.Variable((4, 4), symmetric=True)

problem = cp.Problem(cp.Maximize(x.T @ Sigma @ x), [Sigma[0,0] == 0.2, Sigma[1,1] == 0.1, Sigma[2,2] == 0.3, Sigma[3,3] == 0.1, Sigma[0,1] >= 0,
                                                    Sigma[0,1] == 0, Sigma[0,2] == 0, Sigma[0,3] == 0, Sigma[1,2] == 0, Sigma[1,3] == 0, Sigma[2,3] == 0, Sigma >> 0])
problem.solve()


0.007750000085938451

In [5]:
print('Worst-case sigma', np.sqrt(x.T @ Sigma.value @ x))
print('Sigma', Sigma.value)

Worst-case sigma 0.08803408479639264
Sigma [[ 2.00000003e-01 -1.56969711e-10  3.94620903e-11 -7.89241807e-11]
 [-1.56969711e-10  1.00000001e-01  7.89241815e-11 -1.57848361e-10]
 [ 3.94620903e-11  7.89241815e-11  3.00000005e-01  3.94620908e-11]
 [-7.89241807e-11 -1.57848361e-10  3.94620908e-11  1.00000001e-01]]
